### ISSUE TITLE
chưa sủa được lỗi ở SEO

### ISSUE THREAD

**Issue by TrueVIP** [hacoidev/ophim-core#5]
cụ thể là chưa sửa được lỗi ở phần seo . phim lẻ , phim bộ , chiếu rap, sắp chiếu, tìm kiếm
và muốn có thể sửa được chổ xem phim , phần có thể bạn thích xem nó mặt định không sửa được

**Comment by phantom0803** [comment]
Phim lẻ , phim bộ , chiếu rap hiện tại có thể tạo custom ở phần Phân Loại -> Danh sách trang để tạo và tùy chỉnh SEO title.
Tìm kiếm không nên seo vì rất dễ bị submit link bẩn. tốt nhất nên Disallow ở robots phần tìm kiếm này.

xem phim , phần có thể bạn thích xem bạn có thể tìm sửa trong code của themes
